# Исследование надежности заемщиков

**Описание проекта**

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.
Результаты исследования будут учтены при построении модели кредитного скоринга — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

**Описание данных**

- children — количество детей в семье
- days_employed — общий трудовой стаж в днях
- dob_years — возраст клиента в годах
- education — уровень образования клиента
- education_id — идентификатор уровня образования
- family_status — семейное положение
- family_status_id — идентификатор семейного положения
- gender — пол клиента
- income_type — тип занятости
- debt — имел ли задолженность по возврату кредитов
- total_income — ежемесячный доход
- purpose — цель получения кредита

**Цели исследования:** 
- определить, как влияет семейное положение и количество детей клиента на факт погашения кредита в срок;
- рассмотреть зависимость между уровнем дохода и возвратом кредита в срок;
- изучить разные цели кредита и их влияние на его возврат в срок.

## Откроем таблицу и изучим общую информацию о данных

**Задание 1. Импортируем библиотеку pandas. Преобразуем данные из csv-файла в датафрейм и сохраним в переменную `data`. Путь к файлу:**

`/datasets/data.csv`

In [1]:
import pandas as pd

try:
    data = pd.read_csv('/datasets/data.csv')
except:
    data = pd.read_csv('https://code.s3.yandex.net/datasets/data.csv')

**Задание 2. Выведем первые 20 строчек датафрейма `data` на экран.**

In [2]:
data.head(20)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42               высшее             0   
1          1   -4024.803754         36              среднее             1   
2          0   -5623.422610         33              Среднее             1   
3          3   -4124.747207         32              среднее             1   
4          0  340266.072047         53              среднее             1   
5          0    -926.185831         27               высшее             0   
6          0   -2879.202052         43               высшее             0   
7          0    -152.779569         50              СРЕДНЕЕ             1   
8          2   -6929.865299         35               ВЫСШЕЕ             0   
9          0   -2188.756445         41              среднее             1   
10         2   -4171.483647         36               высшее             0   
11         0    -792.701887         40              среднее             1   
12         0            NaN         65              среднее             1   
13         0   -1846.641941         54  неоконченное высшее             2   
14         0   -1844.956182         56               высшее             0   
15         1    -972.364419         26              среднее             1   
16         0   -1719.934226         35              среднее             1   
17         0   -2369.999720         33               высшее             0   
18         0  400281.136913         53              среднее             1   
19         0  -10038.818549         48              СРЕДНЕЕ             1   

       family_status  family_status_id gender income_type  debt  \
0    женат / замужем                 0      F   сотрудник     0   
1    женат / замужем                 0      F   сотрудник     0   
2    женат / замужем                 0      M   сотрудник     0   
3    женат / замужем                 0      M   сотрудник     0   
4   гражданский брак                 1      F   пенсионер     0   
5   гражданский брак                 1      M   компаньон     0   
6    женат / замужем                 0      F   компаньон     0   
7    женат / замужем                 0      M   сотрудник     0   
8   гражданский брак                 1      F   сотрудник     0   
9    женат / замужем                 0      M   сотрудник     0   
10   женат / замужем                 0      M   компаньон     0   
11   женат / замужем                 0      F   сотрудник     0   
12  гражданский брак                 1      M   пенсионер     0   
13   женат / замужем                 0      F   сотрудник     0   
14  гражданский брак                 1      F   компаньон     1   
15   женат / замужем                 0      F   сотрудник     0   
16   женат / замужем                 0      F   сотрудник     0   
17  гражданский брак                 1      M   сотрудник     0   
18    вдовец / вдова                 2      F   пенсионер     0   
19         в разводе                 3      F   сотрудник     0   

     total_income                                 purpose  
0   253875.639453                           покупка жилья  
1   112080.014102                 приобретение автомобиля  
2   145885.952297                           покупка жилья  
3   267628.550329              дополнительное образование  
4   158616.077870                         сыграть свадьбу  
5   255763.565419                           покупка жилья  
6   240525.971920                       операции с жильем  
7   135823.934197                             образование  
8    95856.832424                   на проведение свадьбы  
9   144425.938277                 покупка жилья для семьи  
10  113943.491460                    покупка недвижимости  
11   77069.234271       покупка коммерческой недвижимости  
12            NaN                         сыграть свадьбу  
13  130458.228857                 приобретение автомобиля  
14  165127.911772              покупка жилой недвижимости  
15  116820.904450 

**Задание 3. Выведем основную информацию о датафрейме с помощью метода `info()`.**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


## Предобработка данных

### Удаление пропусков

**Задание 4. Выведем количество пропущенных значений для каждого столбца. Используем комбинацию двух методов.**

In [4]:
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

**Задание 5. В двух столбцах есть пропущенные значения. Один из них — `days_employed`. Пропуски в этом столбце мы обработаем на следующем этапе. Другой столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Например, у человека с типом занятости `сотрудник` пропуск в столбце `total_income` должен быть заполнен медианным доходом среди всех записей с тем же типом.**

In [5]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == t), 'total_income'].median()

### Обработка аномальных значений

**Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. Таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработаем значения в этом столбце: заменим все отрицательные значения положительными с помощью метода `abs()`.**

In [6]:
data['days_employed'] = data['days_employed'].abs()

**Задание 7. Для каждого типа занятости выведем медианное значение трудового стажа `days_employed` в днях.**

In [7]:
data.groupby('income_type')['days_employed'].agg('median')

income_type
безработный        366413.652744
в декрете            3296.759962
госслужащий          2689.368353
компаньон            1547.382223
пенсионер          365213.306266
предприниматель       520.848083
сотрудник            1574.202821
студент               578.751554
Name: days_employed, dtype: float64

У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставим их как есть.

**Задание 8. Выведем перечень уникальных значений столбца `children`.**

In [8]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5], dtype=int64)

**Задание 9. В столбце `children` есть два аномальных значения. Удалим строки, в которых встречаются такие аномальные значения из датафрейма `data`.**

In [9]:
data = data[(data['children'] != -1) & (data['children'] != 20)]

**Задание 10. Ещё раз выведем перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.**

In [10]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5], dtype=int64)

### Удаление пропусков (продолжение)

**Задание 11. Заполним пропуски в столбце `days_employed` медианными значениями по каждого типа занятости `income_type`.**

In [11]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == t), 'days_employed'].median()

**Задание 12. Убедимся, что все пропуски заполнены. Проверим себя и ещё раз выведем количество пропущенных значений для каждого столбца с помощью двух методов.**

In [12]:
data.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### Изменение типов данных

**Задание 13. Заменим вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.**

In [13]:
data['total_income'] = data['total_income'].astype(int)

### Обработка дубликатов

**Задание 14. Обработаем неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведем их к нижнему регистру.**

In [14]:
data['education'] = data['education'].str.lower()

**Задание 15. Выведем на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалим их.**

In [15]:
data.duplicated().sum()

71

In [16]:
data = data.drop_duplicates()

### Категоризация данных

**Задание 16. На основании диапазонов, указанных ниже, создадим в датафрейме `data` столбец `total_income_category` с категориями:**

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


**Например, кредитополучателю с доходом 25000 назначим категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используем собственную функцию с именем `categorize_income()` и метод `apply()`.**

In [17]:
def categorize_income(income):
    try:
        if 0 <= income <= 30000:
            return 'E (0–30000)'
        elif 30001 <= income <= 50000:
            return 'D (30001–50000)'
        elif 50001 <= income <= 200000:
            return 'C (50001–200000)'
        elif 200001 <= income <= 1000000:
            return 'B (200001–1000000)'
        elif income >= 1000001:
            return 'A (1000001 и выше)'
    except:
        pass

In [18]:
data['total_income_category'] = data['total_income'].apply(categorize_income)

**Задание 17. Выведем на экран перечень уникальных целей взятия кредита из столбца `purpose`.**

In [19]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее об

**Задание 18. Создадим функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:**

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.

Используем собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучим данные в столбце `purpose` и определим, какие подстроки помогут нам правильно определить категорию.

In [20]:
def categorize_purpose(row):
    try:
        if 'автом' in row:
            return 'операции с автомобилем'
        elif 'жил' in row or 'недвиж' in row:
            return 'операции с недвижимостью'
        elif 'свад' in row:
            return 'проведение свадьбы'
        elif 'образов' in row:
            return 'получение образования'
    except:
        return 'нет категории'

In [21]:
data['purpose_category'] = data['purpose'].apply(categorize_purpose)

### Шаг 3. Исследуем данные и ответим на вопросы

#### 3.1 Есть ли зависимость между количеством детей и возвратом кредита в срок?

In [22]:
#создадим сводную таблицу и сгруппируем данные по столбцу children
data_children_pivot = data.pivot_table(index=['children'], values='debt', aggfunc= {'count','sum'})
#переименуем названия столбцов
data_children_pivot = data_children_pivot.rename(columns={'count': 'total', 'sum': 'target'})
#добавим в сводную таблицу новый столбец share со значениями, показывающими долю просрочек
data_children_pivot['share'] = data_children_pivot['target'] / data_children_pivot['total']
#отсортируем сводную таблицу по столбцу share в порядке убывания
data_children_pivot.sort_values(by = 'share', ascending = False)

total  target     share
children                         
4            41       4  0.097561
2          2052     194  0.094542
1          4808     444  0.092346
3           330      27  0.081818
0         14091    1063  0.075438
5             9       0  0.000000

**Вывод:** Наибольшая доля задолженностей по возврату кредитов наблюдается среди клиентов с 4 детьми в семье.  Можно предположить, что это связано с большим количеством непредвиденных расходов.

Самая низкая доля просрочек по кредиту приходится на клиентов без детей. Логично, что у данной категории заемщиков меньше финансовых затрат, следовательно более высокая платежеспособность в отличие от семей с детьми. 

Что касается семей с 5 детьми, кажется нецелесообразным делать вывод из-за небольшого количества данных в этой категории.

Также можно отметить, что если не учитывать группы с 3, 4 и 5-ю детьми, то доля задолженностей по возврату кредитов имеет тенденцию к возрастанию при увеличении количества детей в семье. 

#### 3.2 Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [23]:
#создадим сводную таблицу и сгруппируем данные по столбцу family_status
data_family_pivot = data.pivot_table(index=['family_status'], values='debt', aggfunc= {'count','sum'})
#переименуем названия столбцов
data_family_pivot = data_family_pivot.rename(columns={'count': 'total', 'sum': 'target'})
#добавим в сводную таблицу новый столбец share со значениями, показывающими долю просрочек
data_family_pivot['share'] = data_family_pivot['target'] / data_family_pivot['total']
#отсортируем сводную таблицу по столбцу share в порядке убывания
data_family_pivot.sort_values(by = 'share', ascending = False)

total  target     share
family_status                                 
Не женат / не замужем   2796     273  0.097639
гражданский брак        4134     385  0.093130
женат / замужем        12261     927  0.075606
в разводе               1189      84  0.070648
вдовец / вдова           951      63  0.066246

**Вывод:** В данном случае  так же присутствует зависимость. Согласно сводной таблице, наибольшая доля просрочек по кредиту приходится на клиентов, не состоящих в официальном браке (с семейным положением ‘не женат / не замужем’ и ‘гражданский брак’).

Более надежными заемщиками оказались те клиенты, которые когда-то состояли в официальном браке, но к настоящему времени находятся в разводе или овдовели.

#### 3.3 Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [24]:
#создадим сводную таблицу и сгруппируем данные по столбцу total_income_category
data_income_pivot = data.pivot_table(index=['total_income_category'], values='debt', aggfunc= {'count','sum'})
#переименуем названия столбцов
data_income_pivot = data_income_pivot.rename(columns={'count': 'total', 'sum': 'target'})
#добавим в сводную таблицу новый столбец share со значениями, показывающими долю просрочек
data_income_pivot['share'] = data_income_pivot['target'] / data_income_pivot['total']
#отсортируем сводную таблицу по столбцу share в порядке убывания
data_income_pivot.sort_values(by = 'share', ascending = False)

total  target     share
total_income_category                         
E (0–30000)               22       2  0.090909
C (50001–200000)       15921    1353  0.084982
A (1000001 и выше)        25       2  0.080000
B (200001–1000000)      5014     354  0.070602
D (30001–50000)          349      21  0.060172

**Вывод:** Из-за небольшого объема выборки в категориях E, A и D будет целесообразно сравнить категории C (50001–200000 рублей) и B (200001–1000000 рублей). 

Очевидно, что заемщики с доходом от 50001 до 200000 рублей более склонны к риску просрочить возврат кредита. Более надежными клиентами оказались люди с постоянным доходом в диапазоне от 200001 до 1000000 рублей.

#### 3.4 Как разные цели кредита влияют на его возврат в срок?

In [25]:
#создадим сводную таблицу и сгруппируем данные по столбцу purpose_category
data_purpose_pivot = data.pivot_table(index=['purpose_category'], values='debt', aggfunc= {'count','sum'})
#переименуем названия столбцов
data_purpose_pivot = data_purpose_pivot.rename(columns={'count': 'total', 'sum': 'target'})
#добавим в сводную таблицу новый столбец share со значениями, показывающими долю просрочек
data_purpose_pivot['share'] = data_purpose_pivot['target'] / data_purpose_pivot['total']
#отсортируем сводную таблицу по столбцу share в порядке убывания
data_purpose_pivot.sort_values(by = 'share', ascending = False)

total  target     share
purpose_category                                 
операции с автомобилем     4279     400  0.093480
получение образования      3988     369  0.092528
проведение свадьбы         2313     183  0.079118
операции с недвижимостью  10751     780  0.072551

**Вывод:** Зависимость возврата кредита в срок от цели кредита очевидна. Чаще всего наблюдаются просрочки среди клиентов, если целью их кредита выступают операции с автомобилем или получение образования. 

Самая низкая доля просрочек приходится на клиентов, оформивших кредит для операций с недвижимостью. Вероятно, в данном случае клиенты более ответственны и платежеспособны, так как имеют дело с наиболее дорогостоящими объектами.

#### 3.5 Приведем возможные причины появления пропусков в исходных данных.

Информация при вводе данных может быть внесена некорректно или намеренно не внесена. Кроме того, может возникнуть техническая ошибка при вводе данных, сохранении или открытии файла.

#### 3.6 Объясним, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.

Медианное значение позволяет наиболее корректно заполнить пропуски, особенно если представлен диапазон с сильно выделяющимися значениями.

### Шаг 4: Общий вывод.

Наблюдается зависимость между возвратом кредита в срок и такими параметрами, как наличие ребенка/детей, семейное положение, уровень дохода и цель кредита. 

Согласно вышепредставленным данным, клиенты, которые рискуют просрочить платеж по кредиту: 
- имеют четверо детей в семье;
- не состоят в официальном браке, а именно в статусе "не женат / не замужем" или проживают в гражданском браке;
- получают постоянный доход в размере от 30001 до 50000 рублей;
- берут кредиты для покупки автомобиля или получения образования.

Также есть необходимость охарактеризовать надежных заемщиков. Кредитоспособные клиенты:
- не имеют детей;
- находятся в разводе или в статусе "вдовы / вдовца";
- имеют стабильный заработок от 200001 до 1000000 рублей;
- оформляют кредиты для покупки недвижимости.

Для исследования использовалась таблица, содержащая важную информацию о количестве детей в семье, общем трудовом стаже, возрасте клиента, уровне образования клиента, семейном положении, типе занятости, ежемесячном доходе, цели получения кредита и, конечно, информацию о задолженности.

Для более точного анализа данных на этапе предобработки пропуски в столбцах total_income и days_employed были заполнены медианными значениями. В столбце children были удалены строки с аномальными знчениями. Тип данных в столбце total_income был изменен на целочисленный с помощью метода astype(). Были обработаны неявные дубликаты в столбце education, путем приведения их к нижнему регистру.
